### ISSUE TITLE
Datatype page

### ISSUE THREAD

**Issue by mujerheed** [zuri-training/QR-gen-prt-51#104]

**Comment by HoneyLight** [comment]
Implemented datatype  page design and made it responsive for desktop and mobile view.

![datatype destop view1](https://user-images.githubusercontent.com/98122126/183937586-37ff9baa-f0a3-4ef1-8ff4-abec2bfc9dbf.png)
![datatype destop view2](https://user-images.githubusercontent.com/98122126/183937732-50062c54-6a59-4827-9acc-c0df21c66a7a.png)
![datatype mobile view](https://user-images.githubusercontent.com/98122126/183937828-4256ef80-2586-492e-9041-d896c3cc6e65.png)
