### ISSUE TITLE
AboutPage

### ISSUE THREAD

**Issue by Petsamuel** [zuri-training/QR-gen-prt-51#2]
@Saadiq-Byte 
 

- [x] responsible for the About Page
- [x]  completed by @HoneyLight

**Comment by Saadiq-Byte** [comment]
Currently awaiting the header and footer to proceed.

**Comment by Petsamuel** [comment]
- [x] done by @HoneyLight

**Comment by HoneyLight** [comment]
Implemented the About Us page and made it responsive for bot mobile and desktop view.

![About-Us desktop view](https://user-images.githubusercontent.com/98122126/183943985-1ec86062-a390-4df5-9e92-c36cec171881.png)
![About-Us mobile view](https://user-images.githubusercontent.com/98122126/183944033-cc6939ce-177f-4b08-b01f-8f551ce25c0e.png)
