### ISSUE TITLE
Success Page

### ISSUE THREAD

**Issue by Petsamuel** [zuri-training/QR-gen-prt-51#61]
- [ ] frontend Success page by @HoneyLight

**Comment by HoneyLight** [comment]
Implemented the success page and made it responsive for desktop and mobile view.


![success page desktop view](https://user-images.githubusercontent.com/98122126/183946288-caf23035-dbfc-472b-b0cd-289672bc88db.png)
![success page mobile view](https://user-images.githubusercontent.com/98122126/183946358-bffd624a-8e31-4ea3-82ca-e999dc4b6f88.png)
